In [1]:
#Creating a neural network
import torch
import torchvision
from torchvision import transforms, datasets

In [3]:
# Loading data
train = datasets.MNIST('data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))

test = datasets.MNIST('data', train=False, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor()
                       ]))


trainset = torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset = torch.utils.data.DataLoader(test, batch_size=10, shuffle=False)

In [4]:
import torch.nn as nn
import torch.nn.functional as F

In [8]:
# Feed forword nn which is used input to output
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        # image shape 28*28 - Input - 
        # Output 64 for example
        self.fc1 = nn.Linear(28*28, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.fc4 = nn.Linear(64, 10)
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)
        return x


net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=10, bias=True)
)


In [9]:
# Feed forword nn which is used input to output
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        # image shape 28*28 - Input - 
        # Output 64 for example
        self.fc1 = nn.Linear(28*28, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, 64)
        self.fc4 = nn.Linear(64, 10)
    # This method can have logic behind
    def forward(self, x):
        # rectified linerar Activation functions F.relu
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        # Probability distributions
        # dim=1 is distributing accross the actual data
        return F.log_softmax(x, dim=1)


net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=10, bias=True)
)


In [10]:
X = torch.randn((28,28))

In [11]:
X

tensor([[-2.8584e-01,  6.5322e-01,  1.4896e+00, -1.1448e+00, -9.7727e-02,
         -1.7256e+00, -1.0139e+00, -1.0629e+00,  2.7623e-01,  2.0474e-01,
          5.5281e-01,  3.6988e-01,  1.4405e-02, -4.5491e-01, -7.6401e-01,
         -2.2687e-01, -9.8756e-01, -1.4620e+00,  7.6469e-01,  8.5175e-01,
          4.9680e-01,  1.4455e-01,  6.5740e-01,  8.3644e-01,  2.3022e-01,
          2.1287e-01, -1.2660e+00, -6.4871e-01],
        [ 3.8552e-01,  5.5033e-01, -1.9267e+00, -1.0450e+00, -1.5224e+00,
         -3.8215e-01, -1.8839e+00, -5.3730e-01,  1.0646e-01,  3.6821e-01,
          1.8578e+00, -5.1205e-01,  1.0363e+00, -1.0774e+00,  4.9184e-01,
         -1.2556e+00,  7.1954e-01, -1.3256e+00, -6.3197e-02, -4.3612e-01,
         -1.9210e+00,  2.2810e-01,  2.6023e+00,  1.3009e+00, -9.3690e-01,
         -2.4003e-01, -5.9396e-01, -2.2730e-01],
        [ 3.3474e-01,  1.6958e-01,  1.1223e+00,  1.3194e+00, -5.1200e-01,
          9.6954e-01, -1.5390e-02, -7.4799e-01,  6.1433e-01, -4.9767e-01,
          5.97

In [12]:
X = X.view(-1, 28*28)

In [13]:
X

tensor([[-2.8584e-01,  6.5322e-01,  1.4896e+00, -1.1448e+00, -9.7727e-02,
         -1.7256e+00, -1.0139e+00, -1.0629e+00,  2.7623e-01,  2.0474e-01,
          5.5281e-01,  3.6988e-01,  1.4405e-02, -4.5491e-01, -7.6401e-01,
         -2.2687e-01, -9.8756e-01, -1.4620e+00,  7.6469e-01,  8.5175e-01,
          4.9680e-01,  1.4455e-01,  6.5740e-01,  8.3644e-01,  2.3022e-01,
          2.1287e-01, -1.2660e+00, -6.4871e-01,  3.8552e-01,  5.5033e-01,
         -1.9267e+00, -1.0450e+00, -1.5224e+00, -3.8215e-01, -1.8839e+00,
         -5.3730e-01,  1.0646e-01,  3.6821e-01,  1.8578e+00, -5.1205e-01,
          1.0363e+00, -1.0774e+00,  4.9184e-01, -1.2556e+00,  7.1954e-01,
         -1.3256e+00, -6.3197e-02, -4.3612e-01, -1.9210e+00,  2.2810e-01,
          2.6023e+00,  1.3009e+00, -9.3690e-01, -2.4003e-01, -5.9396e-01,
         -2.2730e-01,  3.3474e-01,  1.6958e-01,  1.1223e+00,  1.3194e+00,
         -5.1200e-01,  9.6954e-01, -1.5390e-02, -7.4799e-01,  6.1433e-01,
         -4.9767e-01,  5.9772e-01,  9.

In [14]:
output = net(X)

In [15]:
output

tensor([[-2.1723, -2.1648, -2.1615, -2.3695, -2.3121, -2.3836, -2.4088, -2.3151,
         -2.2951, -2.5019]], grad_fn=<LogSoftmaxBackward>)

In [ ]:
#grad_fn Graden fuction